### ISSUE TITLE
Issue with grunt server task

### ISSUE THREAD

**Issue by micjamking** [yeoman/yeoman#1092]
After doing a fresh install via `npm cache clean && npm install -g yo grunt-cli bower` and creating a new webapp project using `yo webapp`, I cannot get grunt server to load the preview. 

I receive no errors in the console; here is the output when running grunt server:

```
Running "server" task

Running "clean:server" (clean) task
Cleaning ".tmp"...OK

Running "concurrent:server" (concurrent) task

    Running "coffee:dist" (coffee) task
    File .tmp/scripts/hello.js created.

    Done, without errors.

    Running "compass:server" (compass) task

    Done, without errors.

Running "connect:livereload" (connect) task
Starting connect web server on localhost:9000.

Running "open:server" (open) task

Running "watch" task
Waiting...
```

...however, my browser (Chrome Canary 29.0) simply hangs trying to load http://localhost:9000, and I receive the following error after a timeout: Unable to load the webpage because the server sent no data.
Error code: ERR_EMPTY_RESPONSE

I'm able to run all other grunt tasks, without error, just launching the server seems to be the issue. I've also tried changing port number, which makes no difference, I still receive the same error.

Any help would be appreciated.

Thanks

**Comment by gpfiel** [comment]
I tryed to npm install connect-livereload and not work, anyone knows what can i do?

**Comment by DerekHoffman** [comment]
Worst part for me is that I am getting no error and the window is just not showing up. Do I need to do something in my IIS?

Also I moved my files into TFS and used Yeoman to actually build the project originally. (got a new computer for work)

I installed Node.js NPM install / Bower / and grunt am I missing something?

**Comment by heshantha** [comment]
set PATH=C:\Ruby200-x64\bin;%PATH%

**Comment by rodsilver83** [comment]
I had this error when I run $grunt serve

Running "serve" task

Running "clean:server" (clean) task
>> 1 path cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "concurrent:server" (concurrent) task
    Warning:  Use --force to continue.
        
        Aborted due to warnings.

-The problem is that, the log has no warnings, so when I use, grunt serve --force, I got the opportunity to see the full task log, and I see that in my case I have a sintax problem in one of my scss, files, this compilation error couses the serve task to not run properly, I fixed my scss files and that worked for me.
