### ISSUE TITLE
Why is Jasmine used as default instead of Mocha?

### ISSUE THREAD

**Issue by paulmillr** [yeoman/yeoman#117]
Jasmine is a bloated and has great problems with support. For example, maintainer firstly commented on opened pull request after nine months.

Mocha has very flexible syntax via Chai.js, much more features and cool reporters.

**Comment by LechDvorak** [comment]
I think you have a little more flexibility when using Mocha, since you can pick your own assertion library and your own mocking library. This however also comes with a price of a slightly more complex setup and some additional dependencies. Overall I think it depends on each project or your personal preference which of these libraries you want to use. When using Jasmine this does not exclude you from using Sinon. You can still benefit for example from its fake server. Both frameworks are perfectly able to do the job. As of Jasmine 2.x, I think Jasmine is back in the race with Mocha. Interesting thoughts also here [https://www.apriorit.com/dev-blog/372-testing-javascript-with-jasmine](https://www.apriorit.com/dev-blog/372-testing-javascript-with-jasmine)
