### ISSUE TITLE
grunt server does'nt create .tmp directory

### ISSUE THREAD

**Issue by mrtnbroder** [yeoman/yeoman#1209]
I created a new project with 'yo webapp' with sass bootstrap option selected and after it installed all required modules, I ran 'grunt server'. Everything compiles fine, no errors but the main.css is not created. I can see that there is no .tmp folder created, so I think that is the problem. However, I have no idea why...

```
Running "server" task
Running "clean:server" (clean) task
Running "concurrent:server" (concurrent) task
Running "copy:styles" (copy) task
Done, without errors.

Elapsed time
copy:styles  2s
Total        2s

Running "compass:dist" (compass) task
Running "compass:server" (compass) task
Done, without errors.

Elapsed time
compass         2s
compass:dist    260ms
compass:server  236ms
Total           3s

Running "autoprefixer:dist" (autoprefixer) task
Running "connect:livereload" (connect) task
Started connect web server on 127.0.0.1:9000.

Running "watch" task
Waiting...^C% 
```

**Comment by honrust** [comment]
A bit late perhaps... I had the same problem. In my case the problem was that compass did not find any *.scss files. Just by renaming my CSS from .css to .scss, compass was satisfied and the .tmp dir got created, so the grunt process could continue without problems. Took me a couple of hours to discover this :-(
