### ISSUE TITLE
update-notifier-bower.yml missing from my install.

### ISSUE THREAD

**Issue by landed1** [yeoman/yeoman#1294]
Error: EACCES, permission denied '/Users/calvin/.config/configstore/update-notifier-bower.yml'
You don't have access to this file.

In fact this file doesn't exist for me - I tried reinstalling yeoman as well. This then causes bower to not get the files it needs inside the project.

**Comment by deepakkaithwas** [comment]
I just fixed it in Windows.
I have done three things, which one have fixed it I am not sure.
1. Run cmd prompt as administrator.
2. takeown /? this command is equivalent to chown (linux) but for windows.
3. cacls -cacls <file or directory> /E /T /G <user>:F
4. simply go in $USER /Users/calvin/.config/configstore/ and make files unhidden.

it worked for me like charm.
I have been trying to fix this since many days.
