### ISSUE TITLE
request: use jit-grunt instead of load-npm-tasks

### ISSUE THREAD

**Issue by eckdanny** [yeoman/yeoman#1382]
Typically the first thing I do after scaffolding is switch out `load-npm-tasks` for `jit-grunt` ([npm](https://www.npmjs.org/package/jit-grunt)). Submitted to yeoman/yeoman since any generator that produces a Gruntfile can use the jit loader. 

Here's a [patch](https://gist.github.com/eckdanny/b17c9565d7d73f22665a) if that is helpful.

**Comment by nickautomatic** [comment]
I wonder if this is worth taking another look at. jit-grunt now seems to be pretty good at finding tasks: in fact, I swapped it out in an existing webapp-based project, and found it actually involved *less* configuration: I'd had to add a custom pattern to load-grunt-tasks to get it to find "assemble"; jit-grunt found assemble without any custom configuration at all.

eg. I replaced:

    require('load-grunt-tasks')(grunt, { pattern: ['grunt-*', 'assemble'] });

...with:

   require('jit-grunt')(grunt); 

So in this case, having jit-grunt would actually have made it *easier* to add a custom task (certainly for me - a relative beginner with Grunt - it took quite a lot of head-scratching to get assemble to work with yo webapp; with jit-grunt it would have just worked). jit-grunt now searches for tasks in three different places ("grunt-task", "grunt-contrib-task", and "task"), whereas load-grunt-tasks, as I understand it, only looks for the first of these with its default config.

Looking at jit-grunt's history, I think its task-finding functionality was overhauled in Oct 2014 (after this issue was closed). As far as I can see, it's now not only much faster than load-grunt-tasks but also requires no more - and possibly less - configuration.

**Comment by nickautomatic** [comment]
Sorry, added a comment to this thread, but then decided [here](https://github.com/yeoman/generator-webapp/pull/278#issuecomment-97408718) would be a more appropriate place for it, so I deleted it. Leaving this here just in case anyone got a notification.
