### ISSUE TITLE
404: http://yeoman.io/migrate.html 

### ISSUE THREAD

**Issue by sturobson** [yeoman/yeoman#1416]
So in terminal I typed... `npm install yeoman -g` (which is probably wrong, but...) and got this printed out after hitting enter...

npm WARN deprecated yeoman@0.9.6: The Yeoman CLI is deprecated. See http://yeoman.io/migrate.html for more info.

going to http://yeoman.io/migrate.html gives me a 404

**Comment by jamesfry** [comment]
I've just hit this too (it's been some time since I've used yeoman). When searching for the message "the Yeoman CLI is deprecated" given when installing yeoman, the first hit is an NPM repository page (https://www.npmjs.com/package/yeoman) that links to http://yeoman.io/migrate.html. 

Would you consider putting a page back at that URL or adding a redirect, given that the page is linked both from packages that are still active in the npm repository and linked to from numerous other sites?

**Comment by adriancooney** [comment]
Just hit this too, probably should consider adding something there since old guides still have `yeoman`.

**Comment by SBoudrias** [comment]
I mean... this was over 2 years ago... You should check dates on the tutorials you're reading.
