### ISSUE TITLE
Local Npm module "grunt-minify-html" not found. Is it installed?

### ISSUE THREAD

**Issue by emfluenceindia** [yeoman/yeoman#1481]
Hi,
I am absolutely new to YeoMan world! I installed the software using npm and said "yes" to every question npm installer asked me during the process.

Then I went ahead and installed the polymer generator using npm install -g polyer-generator which seemed to be generated because I can see a lot of core elements are added inside bower_components folder.

However, I was prompted with a considerable number of "overwrite messages" during the installation (of  polymer-generator) and I kept pressing "y" for all.

Now that when I am trying to grunt-serve inside my polymer project folder I am getting the following error message: Local Npm module "grunt-minify-html" not found. Is it installed?

I am on Windows 8.1 PC.

What I am doing wrong? Should I completely remove yomen from my system and do a fresh install? If yes, how can I remove yeoman in full? Is there any tutorial?

Regards,
Subrata Sarkar

Attached screenshot:
![error](https://cloud.githubusercontent.com/assets/11072678/6314067/d48c4cc4-b9f2-11e4-817a-dbc82e003ea5.jpg)

**Comment by addyosmani** [comment]
The overwrite messages usually occur when you've tried to scaffold out something, accidentally killed the process and restarted again (or are using the same directory for this a few times). Don't worry. Happens to folks all the time :)

From your error log it looks like you still need to install Ruby and Sass before that part of the scaffolding will work. You should also run `npm install` in the directory you scaffolded out your files in so that any dependencies, like the one you mentioned are missing, are in fact installed.
