### ISSUE TITLE
Improve the yeoman generator API documentation

### ISSUE THREAD

**Issue by deslee** [yeoman/yeoman#1485]
[The generator documentation](http://yeoman.github.io/generator/index.html) leaves a lot to be desired. 

As a developer, I would like a search feature to find certain methods described in the "[creating a generator](http://yeoman.io/authoring/file-system.html)" guide.  For example, if I want to quickly find the API for `generator.destinationRoot`, I don't want to navigate to each of the classes / mixins to find that method.

A good example of a search feature is the [API docs for angular-ui](http://angular-ui.github.io/ui-router/site/#/api/ui.router)

Also, I would like a version number to know if the API documentation I'm looking at is for the latest version or if it is for a previous version.

**Comment by SBoudrias** [comment]
Contributions gladly accepted on this topic.

I don't think anyone from the core team have free time for this currently.

**Comment by eddiemonge** [comment]
We definitely do want to version the api but its a bit rough at the moment until we have a stable 1.0.0 release of generator as things change fast and keeping up with the docs is harder. we could spend more time automating the making of the docs but as Simon said, core team has all been pretty busy. Im trying to free up more time to do more but that pesky personal life keeps getting in the way. After June should be better.

**Comment by pacav69** [comment]
I agree a search capability would be very useful especially for developers looking for howto use or know the syntax of a function.

**Comment by mischah** [comment]
Hej, I would like to work on this.

**Comment by eddiemonge** [comment]
@mischah awesome! any help is appreciated

**Comment by mischah** [comment]
Okay cool.

Let’s split this up into:

1. [ ] Add a search box into the docs
2. [ ] Add a version switcher

**Comment by mischah** [comment]
I’m almost done with »Add a search box into the docs«

I did some research regarding JSDoc templates and tried a few.
That made me sad. There are just 3 with search functionality. And just one of them makes sense to use for the Yeoman docs because it’s looks good, has a good UX and offers all the features of the default template.

The good news: The one is a extremely new kid on the block (first release 4 days ago) but its super awesome.

Im just waiting for on PR of mine to get merged: https://github.com/nhnent/tui.jsdoc-template/pull/4

After that the Yeoman docs could look like that:

<img width="965" alt="tui-jsdoc-template-01" src="https://cloud.githubusercontent.com/assets/441011/20198550/896c10d8-a7a5-11e6-9093-0768482ee7d2.png">

<img width="1042" alt="tui-jsdoc-template-02" src="https://cloud.githubusercontent.com/assets/441011/20198564/949f34f8-a7a5-11e6-88a5-0c7a854ebc81.png">

Minus the »API | Examples« navigation which I adress with my PR.

**Comment by mischah** [comment]
PR regarding that searchbox landed https://github.com/yeoman/generator/pull/977 :octocat: 

Next I’m going to try to implement a version switcher for that JSDoc template 😊

**Comment by mischah** [comment]
Update: 

The version switcher is almost done 😗 
https://github.com/nhnent/tui.jsdoc-template/pull/9
