### ISSUE TITLE
fs difference from 0.16.0 vs 0.18.0

### ISSUE THREAD

**Issue by ccit-spence** [yeoman/yeoman#1487]
This is more of a question, did something change within the yeoman-generator versions 0.16.0 to 0.18.0 that would affect the timing of functions?

I have a generator built on 0.16.0 and when upgraded to 0.18.0 it will not work.  

The exact line that fails is `var variables = fs.readFileSync('app/xml-templates/variables.xml','utf8');`

Just before this line is `this.directory('xml-templates/', 'app/xml-templates/');` 

error thrown `Error: ENOENT, no such file or directory 'app/xml-templates/variables.xml'`

This is not a standard generator as it only parses some information to create xml/jelly scripts.  

```
darwin { http_parser: '1.0',
  node: '0.10.33',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.29',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1j' }
cat: Gruntfile.js: No such file or directory
```

**Comment by SBoudrias** [comment]
Yes, now every yeoman file system helpers won't be written to disk until the generator is done (to be exact during the `conflict` phase).

As so, when you use the native `fs.readFileSync()`, the file is not available on disk. For what it's worth, the way you handle it in your generator is flakey and could have failed in multiples instances based on different reason. What we did in 0.18, is normalize the API and made it very clear that file write are asynchronous.

The fix for you is to use `this.fs.read(this.destinationPath(''app/xml-templates/variables.xml''))` (or whatever path method is correct to target the file you want to read)

More on this inside our [release blog post](http://yeoman.io/blog/release-0.18.html). See the "new fs method" section.
