### ISSUE TITLE
npm3 and peerDependencies

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/yeoman#1488]
We currently use `peerDependencies` to have external sub-generators installed automatically with the main generator, eg `generator-mocha` is a peerDependency in `generator-webapp` and installed with it.

npm3 will no longer install `peerDependencies`, which is a very good change, but will impact how we currently use it:

> We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies. - http://blog.npmjs.org/post/110924823920/npm-weekly-5

We should probably have sub-generators in `dependencies` instead.

-

Thoughts?

**Comment by sindresorhus** [comment]
@yeoman/owners

**Comment by SBoudrias** [comment]
So, let's start with a recap on the three ways to run a generator from a generator: `invoke`, `hookFor` and `composeWith`.

`invoke` is pretty bad as it invoke a generator by blocking the current generator (1) and require the other generator to be installed a peer. We should **stop using** `invoke`; and probably deprecate it.

`hookFor` is very bad. In part because it have all the bad parts of `invoke`, but even more horrible, it is running out of bounds and usually the `end` event will be triggered before a hooked generator is completed. It is also very easy for multiple hooked generator to conflict with each other if they all provided prompts and such. **Do not use** `hookFor` at all. Never. Ever! We should also deprecate in a future release.

`composeWith` is super great! You should all use it, and it should be the only way to call another generator.

So, my point is, we should add generators we want to compose with as `dependencies`. Then, when using `composeWith`, pass a `local` option to use the locally installed generator version. This mean the parent generator can rely on the subgenerator version and behavior, and this mean we can get rid of `peerDependencies`. Here's an example:

```js
this.composeWith('mocha', { /* your arguments and options */ }, {
  local: require.resolve('generator-mocha')
});
```

_foot notes_  
1. Invoked generator are kinda synchronous, but are not really so I'm not using the term. But note a generator calling `invoke` is effectively blocked until completion of the invoked generator.

**Comment by eddiemonge** [comment]
that all sounds good to me. Subgenerators should definitely be dependencies instead of peerDeps.

**Comment by olsonpm** [comment]
@SBoudrias - I tried your suggestion and an issue to note is that previously composeWith didn't require the modules to have proper entrypoints (i.e. package.json->"main").  By using require.resolve, this is mandatory.

```
// package.json
...
  "main": "generators/app/index.js"
...
```

**Comment by SBoudrias** [comment]
@olsonpm can you use `require.resolve('generator-x/app')`

**Comment by olsonpm** [comment]
Ah - that does work.  Thanks

**Comment by emanb29** [comment]
+1 npm 3 is making me insane with generator-angular. There should be a requirement, or at least a strict guideline, to use dependencies or devDependencies instead of peerDependencies.

**Comment by lekanojulowo** [comment]
![2015-12-17_202120](https://cloud.githubusercontent.com/assets/11391583/11879547/45b0df6a-a4fc-11e5-96f2-b9ff85324a65.png)

I'm having the above error message, I tried to connect to mongoDB through mongoose.connect. When I installed mongoose using npm install mongoose, it warned me that peerDependency was not installed automatically with npm3+. I will appreciate any useful help.

**Comment by eddiemonge** [comment]
@lekanojulowo please open that on the relevant generator to get help for it.

Closing this as we know what we should do now we need to do it in the relevant generators
