### ISSUE TITLE
Test environment limitation: Can't run 2 generators in same directory

### ISSUE THREAD

**Issue by BLamy** [yeoman/yeoman#1531]
Recently, I had made a contribution to the polymer starter kit generator.

The objective was simple I wanted to make polymer:el prompt "Would you like to include test for your element?"

The work flow looked something like this

`yo polymer`
`Would you like to include the web-component-tester?`

`yo polymer:el foo-bar`
`Would you like to include an import in your elements.html file?`
`Would you like to include test for your element?`

Now here's the catch. If they said they don't want to include the web-component-tester in the main generator it doesn't make sense to even ask them to generate a test when using the el generator. So I conditionally added the second prompt. The generator worked perfect but it was time to write test for it. 

The way PSK was doing their previous test looked like this. 

```
 before(function (done) {
    helpers.run(path.join(__dirname, '../app'))
      .inDir(path.join(__dirname, './tmp'))
      .withArguments(['--skip-install'])
      .withPrompt({
        includeWCT: true
      })
      .on('end', done);
  });

  before(function (done) {
    helpers.run(path.join(__dirname, '../el'))
      .inDir(path.join(__dirname, './tmp'))
      .withArguments(['my-foo'])
      .withPrompt({
        includeImport: false
      })
      .on('end', done);
  });
```

It made sense just run one generator before the other. However, everything from the original generator is deleted before the second generator is run.
After [quite a bit of hacking](https://gist.github.com/robdodson/6e1672f6dc7a3f00b678) I was never actually able to write a test case that would run two generators in the same directory which leads me to believe that it's a limitation in the testing environment.

**Comment by SBoudrias** [comment]
`.inDir()` will empty the directory to make it clean for testing purposes.

You can copy files you rely on for testing `generator:el` manually. It's better to not run two generators in the same directory. This is making your test flakey.

**Comment by BLamy** [comment]
Why would running more then one generator make your test flakey? Wouldn't you want it to be as close to production as possible? 

Not arguing genuinely asking.

**Comment by fluky** [comment]
I have to agree with @BLamy here.  The suggestion to manually setup an environment for running a sub-generator would be fine for unit testing but is a horrible idea for end to end testing.  Plus destroying objects you don't own is just plain bad practice.

If I neglect to call inDir then Yeoman creates its own temporary directory.  Yeoman owns this directory and should be responsible for cleaning it up.  However, if I call inDir, I own the directory.  That means that the directory should be in the correct state when passed to Yeoman and I should be responsible for cleaning it up.  The fact that Yeoman runs rimraf on a directory they don't own is a Bug with a capital B.

For those that stumble upon this here is a working hack to get around this behavior:

```
               helpers.run (path.join (__dirname, '../../app')).withPrompts (this.prompts).inDir (buildDir).on ('end', () => {
                  helpers.testDirectory = function testDirectory (dir, cb) {
                     var resolved;

                     if (!dir) {
                        throw new Error ('Missing directory');
                     }   

                     resolved = path.resolve (dir);
                     mkdirp.sync (resolved);
                     process.chdir (resolved);
                     cb (); 
                  };  

                  helpers.run (path.join (__dirname, '../../entity')).withOptions ({ force: true }).withPrompts (this.entityPrompts).inDir (buildDir).on ('end', () => {
                     this.install (dbname, resolve, reject);
                  }).on ('error', error => reject (`failed to generate entity: ${ error }`, dynamo));
```

Note the **force** option is set because I also don't see a way to handle conflicts with the run context.

This is not the most elegant solution but for my case, since it is a custom script for e2e testing it works.  If I were going to use this in unit testing, or wanted a more elegant solution I would probably use mockery to stub out rimraf.

Since @SBoudrias summarily dismissed this bug without allowing for further discussion I don't expect any changes to come from this.  If there is enough interest I might consider a creating a bolt on that makes this easier, something like an "inMyDir" that acts appropriately and doesn't destroy resources it doesn't own and perhaps even a conflict handler.
