### ISSUE TITLE
Change destinationRoot only break other sub-generators config path.

### ISSUE THREAD

**Issue by lijunle** [yeoman/yeoman#1622]
The [destinationRoot](http://yeoman.io/generator/base.js.html#line695) function updates the destination root path and re-get the storage for config ([line 707](http://yeoman.io/generator/base.js.html#line707)). However, the sub-generator's config is not updated. As a workaround, I manually update other configs by invoke

```js
this.config = this._getStorage();
```

A better approach is to move the `config` into `this.options.env` and share to each sub-generator as property.

**Comment by SBoudrias** [comment]
Not really, because that would then prevent us from making breaking changes to the config API.

**Comment by lijunle** [comment]
I don't get your meaning here. Are you always making breaking changes on config API?

**Comment by SBoudrias** [comment]
@lijunle no, but if we were too at any point in the future, it'd be impossible to do.

**Comment by lijunle** [comment]
@SBoudrias I think we are discussing something not related to this issue.Back

 to the topic, how do you think about the issue? I think it is not making sense to call `this._getStorage()` in each sub-generator.

**Comment by SBoudrias** [comment]
To me, the core issue seems to be that the configuration is not refreshed when it changes in another generator.

**Comment by lijunle** [comment]
@SBoudrias exactly!

**Comment by SBoudrias** [comment]
Actually, here a relevant question is what is the ordering?

Are you calling `composeWith()` before or after `destinationRoot()`? Also, are you sure there's no `.yo-rc.json` file modifying the root of your project automatically?

**Comment by lijunle** [comment]
> Are you calling composeWith() before or after destinationRoot()?

Yes. I change the destination root according the prompting.

> Are you sure there's no .yo-rc.json file modifying the root of your project automatically?

I modified the destination root to be one level deeper. Finally, there are two yo-rc.json files created:

- One in the original destination root. It is created by other sub-generator.
- Another in the new destination root. It is created by the changing root sub-generator.

**Comment by SBoudrias** [comment]
Well so, you want:

1. Prompt for root from the top level generator
2. Call `destinationRoot()`
3. Create your deeper `.yo-rc.json`
4. Only then call `composeWith()`

`destinationRoot()` doesn't have side effects on sub-generators who're in the process of running. And if you have a `.yo-rc.json` in a parent directory, the root of the sub-generators is going to be reset to that directory.

I'm going to close this issue as it's really more a problem with how you organize it than Yeoman itself. The config file is effectively reloaded when it changes, your issue is that they're not pointing to the same one.
