### ISSUE TITLE
How to pass an object as an argument?

### ISSUE THREAD

**Issue by alallier** [yeoman/yeoman#1655]
I specify `this.argument('argumentName', { type: Object, required: true, desc: 'Hello World' });` in my constructor. When this gets parsed it looks like this when calling the program with `yo testProject {"test": 1234}`:

```
arguments: [ '{test:', '1234}' ],
args: [ '{test:', '1234}' ],
```

I have also tried passing the object as a string `yo testProject "{"test": 1234}"` with the same argument and that results in:

```
arguments: [ '{test: 1234}' ],
args: [ '{test: 1234}' ],
```

What is the proper way to specify an object as an argument, so that the argument exists as an object and can be reached by something like `this.argumentName.test` and receive 1234

**Comment by SBoudrias** [comment]
@alallier I think the issue is mainly that command line interfaces are not scripting language. So it doesn't parse language features like an object. It only accepts blobs of texts that it separates on spaces.

You'd want to pass the object as a string and `JSON.parse` it.

That being said, that wouldn't be a great end user experience. Did you consider using `this.option()` instead? e.g. `yo generator --test=1234 --other=foo`

**Comment by alallier** [comment]
I tried doing that but it doesn't work. If I pass `{test: "Hello World"}` it parses as this:

```
arguments: [ '{test:', 'Hello World}' ],
args: [ '{test:', 'Hello World}' ],
```

The above results in two separate arguments.

If I pass `"{test: "Hello World"}"` it parses as:

```
arguments: [ '{test: Hello', 'World}' ],
args: [ '{test: Hello', 'World}' ],
```

The above results in two separate arguments.

So when going to JSON.parse the argument I am only parsing part of the object `{test:` in the first case and `{test: Hello` in the second

**Comment by SBoudrias** [comment]
I think you'll want to open an issue on https://github.com/substack/minimist asking to add support for "strings containing spaces".
