### ISSUE TITLE
the function of generator Can not be used now

### ISSUE THREAD

**Issue by blackcloud2333** [yeoman/yeoman#1687]
as i have the problem that i can find the generator in npm and npms .I have install the generator, i can't  find the generator when i was try to use the yo to generate the template .
how  can i solve the problem ?
![2018-02-23_181115](https://user-images.githubusercontent.com/25345753/36589078-152c6550-18c5-11e8-98fd-2a6b1eec324e.png)
![2018-02-23_181207](https://user-images.githubusercontent.com/25345753/36589086-18f2f618-18c5-11e8-8915-73c8d895bd5e.png)
by the way ,this generator is writed by myself.

**Comment by SBoudrias** [comment]
I'd say 2 things:

1. Run `yo doctor`; it'll find lot of issues that can lead to yo not finding a generator.
2. Are you sure your generator is working properly? This could happens if somehow your generator isn't working. You can test it easily by specifying the path manually `yo ./path/to/my-generator`

**Comment by blackcloud2333** [comment]
i find why  this  problem  is happend .when your files name is  not strictly oby the rule ,this problem will happend .
thakyou for the answer.
i am so sorry for my problem cost your so much time.
