### ISSUE TITLE
Generator doesn't take local installed sub generator but the global installed generator

### ISSUE THREAD

**Issue by StfBauer** [yeoman/yeoman#1702]
Hi, question. I have a generator that uses a sub-generator.
The sub generator is installed in the local generator package via dependency and has a fix define version number.
The sub generator is installed on the client machine in the global node_modules too with an older version.
When I pass in the local generator during the installation still the older global installed will be take.
How can I avoid this?

**Comment by SBoudrias** [comment]
Yeoman will not automatically search to register generators in your own generator directory (there's some technical issue around doing this.)

That's why we recommend using a specific path when using `composeWith`; as such:

```js
this.composeWith(require.resolve('generator-bootstrap/generators/app'));
```

http://yeoman.io/authoring/composability.html

Let me know if this fix your issue!

**Comment by StfBauer** [comment]
Thank you figured out what the issue was. The other generator called all his sub-generators as regular generators instead of using the approach above.
Basically, the correct reference was ignored by the sub-generators.
